// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription

=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For more information, see
 link:#_planning_the_deployment[Planning the deployment], earlier in this guide.
. Ensure that your AWS account is configured correctly, as discussed in the
 link:#_technical_requirements[Technical requirements] section.
. Use the Region selector in the navigation bar to choose the AWS Region where you want to deploy.
. Choose the key pair that you created earlier. In the navigation pane of the https://console.aws.amazon.com/ec2/[Amazon EC2 console^], choose *Key Pairs*, and then choose your key pair from the list.

=== Launch the Quick Start

. Sign in to your AWS account, and launch this Quick Start, as described under Deployment options. The AWS CloudFormation console opens with a prepopulated template. Deployment takes about 30 minutes to complete.
. Choose the correct AWS Region, and then choose Next.
. On the Create stack page, keep the default setting for the template URL, and then choose Next.
. On the Specify stack details page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. When you finish reviewing and customizing the parameters, choose Next.
. On the Configure stack options page, you can set advanced options. When you finish, choose Next.
. On the Review page, review and confirm the template settings. Under Capabilities, select all of the check boxes to acknowledge that the template creates IAM resources that might require the ability to automatically expand macros.
. Choose Create stack to deploy the stack.
. Monitor the stack’s status, and when the status is CREATE_COMPLETE, the Starrocks deployment is ready.
. To view the created resources, choose the Outputs tab.

+
NOTE: Unless you are customizing this Quick Start's templates for your own deployment projects, we recommend that you keep the default settings. For more information, see the https://aws-quickstart.github.io/option1.html[AWS Quick Start Contributor’s Guide^].